name: tapp
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4=4.9.3
  - gensim=3.8.3
  - jupyterlab=2.2.6
  - nltk=3.5
  - nodejs=10.13.0
  - pandas=1.2.0
  - pandas-datareader=0.9.0
  - pip
  - plotly=4.14.3
  - pyarrow=2.0.0
  - python=3.8
  - requests=2.25
  - scikit-learn=0.23.2
  - spacy=2.3.5
  - statsmodels=0.12
  - textblob=0.15.3
  - pip:
    - linearmodels==4.19
    - pynytimes==0.4.2
    - tensorflow==2.4
