name: tapp
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4=4.8.2
  - gensim=3.8.0
  - jupyterlab=1.2.4
  - lxml=4.4.2
  - nltk=3.4.5
  - nodejs=10.13.0
  - pandas=0.25.3
  - pandas-datareader>=0.8.1
  - pip>=19.3.1
  - plotly=4.4.1
  - pyarrow=0.13.0
  - python=3.7
  - requests=2.22.0
  - scikit-learn=0.22.1
  - spacy=2.2.3
  - tensorflow>=2.0
  - textblob=0.15.3
  - pip:
    - nytimesarticle==0.1.0
